name: Ping All Services

on:
  schedule:
    - cron: '*/8 * * * *' # every 15 minutes
  workflow_dispatch: # allow manual trigger

jobs:
  ping-everything:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Clients
        run: |
          sudo apt-get update
          sudo apt-get install -y curl postgresql-client mysql-client

      - name: Ping Render and API Endpoints
        run: |
          echo "🌐 Pinging Web Endpoints..."
          for url in \
            "https://scanify.onrender.com" \
            "https://retechnox.in" \
            "https://movement-science.com" ; do
              echo "Checking $url"
              code=$(curl -s -o /dev/null -w "%{http_code}" "$url")
              echo "→ Status: $code"
              [ "$code" = "200" ] || echo "❌ $url failed with $code"
          done
          echo "✅ Web endpoint checks done."

      - name: Ping MySQL Databases
        env:
          MYSQL1_HOST: ${{ secrets.MYSQL1_HOST }}
          MYSQL1_PORT: ${{ secrets.MYSQL1_PORT }}
          MYSQL1_USER: ${{ secrets.MYSQL1_USER }}
          MYSQL1_PASS: ${{ secrets.MYSQL1_PASS }}
          MYSQL1_NAME: ${{ secrets.MYSQL1_NAME }}

          # MYSQL2_HOST: ${{ secrets.MYSQL2_HOST }}
          # MYSQL2_PORT: ${{ secrets.MYSQL2_PORT }}
          # MYSQL2_USER: ${{ secrets.MYSQL2_USER }}
          # MYSQL2_PASS: ${{ secrets.MYSQL2_PASS }}
          # MYSQL2_NAME: ${{ secrets.MYSQL2_NAME }}
        run: |
          echo "🦦 Checking MySQL Databases..."
          declare -A MYLIST=(
            ["MySQL1"]="$MYSQL1_HOST:$MYSQL1_PORT:$MYSQL1_USER:$MYSQL1_PASS:$MYSQL1_NAME"
          )
          for db in "${!MYLIST[@]}"; do
            IFS=":" read host port user pass name <<< "${MYLIST[$db]}"
            echo "Checking $db ($host)..."
            mysql -h $host -P $port -u $user -p$pass -e "USE $name; SELECT NOW();" \
              && echo "✅ $db OK" || echo "❌ $db failed"
          done

